export const CREATE_CLASSIFICATION = 'CREATE_CLASSIFICATION';
export const GET_ALL_CLASSIFICATIONS = 'GET_ALL_CLASSIFICATIONS';

export const CREATE_ASSESSMENT = 'CREATE_ASSESSMENT';
export const GET_ASSIGNED_ASSESSMENTS = 'GET_ASSIGNED_ASSESSMENTS';
export const GET_EDITABLE_ASSESSMENTS = 'GET_EDITABLE_ASSESSMENTS';
export const LOAD_ASSESSMENT = 'LOAD_ASSESSMENT';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const ADD_QUESTION_TO_ASSESSMENT = 'ADD_QUESTION_TO_ASSESSMENT';

export const CREATE_USER = 'CREATE_USER';
