export const FETCH_CLASSIFICATIONS = 'FETCH_CLASSIFICATIONS';

export const GET_ASSIGNED_ASSESSMENTS = 'GET_ASSIGNED_ASSESSMENTS';
export const GET_EDITABLE_ASSESSMENTS = 'GET_EDITABLE_ASSESSMENTS';
export const GET_ASSESSMENTS = 'GET_ASSESSMENTS';

export const CREATE_ASSESSMENT = 'CREATE_ASSESSMENT';
export const ADD_QUESTION_TO_ASSESSMENT = 'ADD_QUESTION_TO_ASSESSMENT';
export const LOAD_ASSESSMENT = 'LOAD_ASSESSMENT';
export const SUBMIT_ASSESSMENT = 'SUBMIT_ASSESSMENT';

export const CREATE_QUESTION = 'CREATE_QUESTION';
export const LOAD_EDITABLE_QUESTION = 'LOAD_EDITABLE_QUESTION';
export const SAVE_QUESTION = 'SAVE_QUESTION';
export const LOAD_VIEWABLE_QUESTION = 'LOAD_VIEWABLE_QUESTION';
export const SUBMIT_QUESTION_ATTEMPT = 'SUBMIT_QUESTION_ATTEMPT';

export const LOAD_USER = 'LOAD_USER';
